apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "balance.fullname" . }}
  labels:
    {{- include "balance.labels" . | nindent 4 }}
data:
  listens: /ip4/0.0.0.0/udp/7780/quic
  bootstraps: /dns4/kistio-center.kistio/udp/7780/quic/p2p/QmcrAKUhzGuxN8oBJkDHGHnvGr7KVspp1SPA4vVAZBP7LF
  topic-pub: account
  topic-sub: balance
  interval: "100"
