apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kistio-center.fullname" . }}
  labels:
    {{- include "kistio-center.labels" . | nindent 4 }}
data:
  listens: /ip4/0.0.0.0/udp/7780/quic
  seed: kistio-center
  enable-dht-server: "true"
