apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kistio-center.fullname" . }}
  labels:
    {{- include "kistio-center.labels" . | nindent 4 }}
data:
  listens: /ip4/0.0.0.0/udp/7780/quic
  seed: kistio-center
  enable-dht-server: "true"
  bootstrap: /ip4/192.168.136.65/udp/7780/quic/p2p/QmcrAKUhzGuxN8oBJkDHGHnvGr7KVspp1SPA4vVAZBP7LF