apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kistio-center.fullname" . }}
  labels:
    {{- include "kistio-center.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kistio-center.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kistio-center.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kistio-center.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: quic
              containerPort: 7780
              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: LISTENS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kistio-center.fullname" . }}
                  key: listens
            - name: SEED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kistio-center.fullname" . }}
                  key: seed
            - name: ENABLE_DHT_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kistio-center.fullname" . }}
                  key: enable-dht-server
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7788"]
            initialDelaySeconds: 3
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7788"]
            initialDelaySeconds: 3
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
