apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "cloud-secrets-controller.fullname" . }}
  labels:
    {{- include "cloud-secrets-controller.labels" . | nindent 4 }}
webhooks:
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZpVENDQTNHZ0F3SUJBZ0lDQjhvd0RRWUpLb1pJaHZjTkFRRUxCUUF3VmpGVU1CSUdBMVVFQ2hNTGNHOXoKZEdsbExtTm9ZWFF3RndZRFZRUUtFeEJvTUc0NUxuQnZjM1JwWlM1amFHRjBNQ1VHQTFVRUNoTWVZMnh2ZFdRdApjMlZqY21WMGN5NW9NRzQ1TG5CdmMzUnBaUzVqYUdGME1CNFhEVEl5TURjd05URXlNalV5TVZvWERUTXlNRGN3Ck5URXlNalV5TVZvd1ZqRlVNQklHQTFVRUNoTUxjRzl6ZEdsbExtTm9ZWFF3RndZRFZRUUtFeEJvTUc0NUxuQnYKYzNScFpTNWphR0YwTUNVR0ExVUVDaE1lWTJ4dmRXUXRjMlZqY21WMGN5NW9NRzQ1TG5CdmMzUnBaUzVqYUdGMApNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQTVKR243WjJhU214YmYrd2NJemlRCnZGWE9IQkZNYkVCejh1ZjMzKzhvRHhDSjZ4ZlUrWGJZblFuSTl0UkxrOEp4a1ora0d0ck1za0lOdUxmaStJaGwKNWkyWnRoZXJuNjRKazBRRUJ5TnN3RHZjRzZLVFczVzI0WGFnZG9QTkpYWjd0NjJSS2tGb0dGa0gydnVLc0xsNApUUFdQeVhiZi9PSXRJUVQ4TXkxUFhUaTRXQm9PRHVrLzQ1VkRYVC81cUVyNXk2ejB0Q1duS0l6ZlRKaGpvYUM3Ci9sbjFMTzdta1Jjc3RBcUJIWnNVMXgwK1FRYnMzRnI2eDFlL1hZdkFrT2NvTjU2SE1TKzZtU3R6aDh5aFk0TUkKdCtLOXdSTlg0b1RHR09tVEpPQVhBSkFjWVZ2RlpEdXM5N1ppS1gxYjhPT3RXSUluazRuRFdYUVB0eTVWZjU2RQp5Q2d6ZmtlZ3hGamtHK0VWL2hKK3RqRTEySTV0SjdVcllaUjd3QUIyMFM2MzQzc1orU2lnTEV1anB3ckNFcnRWCm4xZEN3YVZXTXJzd1d0NlYwcnZIVnhDb2ZFaWdZV3RVL3c2K3ZERWRDQ3dWOGx4NWR6VmZvSEhpZWdMNmwxUXMKWEFCLzhta0c5Y3VQaDZYeWwwdDFvd3Z6T1dwU280L0gwb2gzeUdxM1p4UmlkbFlsWWg5VGsyNWxNU1ROaWdSYgp3YnY1NEJpQW1LZy82dHBpTytOdjRHMWVlNWVvVkNENUdtVnphUFZwZWgzdnhjZHBvTkN1VmpFWk9ZRENRT3BSCk1ZUnNkWUtqSU5zSDVUQUtvK25kWnNTZTBLVUJ3RFBkMzROZGVSaThyMUdvM1FnaTExR3dDVzRuUmNiU2NWUGEKZ0xKMWhPckc4bU1YK2RVUFhYTHVUcE1DQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS0VNQjBHQTFVZApKUVFXTUJRR0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjREFUQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkCkRnUVdCQlF5NkJRTVg1OG4vOWFONldMbW0vM211d0ovRnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQWEzTHAKN1VML1BBckh1dnFhYWJueWQ3dEt2ZWl0OVJWQTRGaHdmdVdNRjJlVGZ5dHFTMnhZZ0RlRVBsdkdFZ0RYYWpJRQpmbDVCYzJzRCt5U3UxYnZENmlYeVE5NURrV1ltaVJZUnVTM2tLbG8xREFPK29nbmZhWUd4cVFMajBsR3kvSHZxCktZNXlXVGcreTkvN0Vxa294WGczM1pSYWZrcm1VTjBaNE9ldFNZcTZMTE15alprTEN5ZHZXNU9SY2wwNWR6QksKc2owWGI1SWF3Unc0ZjZlWDBBbnFoZjZVaWYwd1REZ1ZjVTZCYU95QWM3MkluejcyRkFuVDcrNWd5UGF6NWkwcgpHVmRXcTljZEhPalNxYjJqTmkxMWlYK2NDeVVkNi9iYm1XT2t1ZzFzUit3M1d4ZG9hUndXOG0vaHkxdE10SUU4CnlhRG02TXV2NXhIYmpNWDAwVWdLZXRMWjQ2ajQyKzhwU2twdGhpQ2JzcldBaEM5bEVCcE5Pc21QK2w2MWtvRmsKZTkzc1hHVFNyNEFVSGdCRVhvdWdjcCt2cHV0UmtEd0cwSGpXNTBmcSt5TnZCNW9HWmJPSWFsa0VoZ0RHMHExTQpYaXZ2elRkcEpzMjhLNk84c21yS0Nnall0d0lTNHFjUGJEa2RJSm5aS0tiWEhpb0dQakNtMUM4bllUOGZERUdtCnZoR2F2Nkgwd1VvQnJHWS93VXZYSkcyazJBeHFobnNtZ0UxNm5yQkFzTHBCcVVXK001VkxGY3BCSFdWNmRTSmoKdHpVVGtncnBEeHczbXo1WGNWaGtZWkd0UStablZUUHFNL3A5UitQWmYzNVA2NkM1Mm9rM2xtUkovNk02ZW4xZwoyQmlKNFViS2R2ZnFGSnhYa2NuSDhxYjljckxkQ2YrbW5jTmpSNnM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: {{ include "cloud-secrets-controller.fullname" . }}
        path: /mutate
        port: {{ .Values.service.port }}
        namespace: {{ .Release.Namespace }}
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    failurePolicy: Fail
    name: "cloud-secrets-manager.h0n9.postie.chat"
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
      scope: "Namespaced"
    namespaceSelector:
      matchLabels:
        cloud-secrets-injector: enabled
