apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-secrets-controller.fullname" . }}
  labels:
    {{- include "cloud-secrets-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      name: http
  selector:
    {{- include "cloud-secrets-controller.selectorLabels" . | nindent 4 }}
