// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: proto/lake.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LakeClient is the client API for Lake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LakeClient interface {
	Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*SendRes, error)
	Recv(ctx context.Context, in *RecvReq, opts ...grpc.CallOption) (*RecvRes, error)
}

type lakeClient struct {
	cc grpc.ClientConnInterface
}

func NewLakeClient(cc grpc.ClientConnInterface) LakeClient {
	return &lakeClient{cc}
}

func (c *lakeClient) Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*SendRes, error) {
	out := new(SendRes)
	err := c.cc.Invoke(ctx, "/Lake/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lakeClient) Recv(ctx context.Context, in *RecvReq, opts ...grpc.CallOption) (*RecvRes, error) {
	out := new(RecvRes)
	err := c.cc.Invoke(ctx, "/Lake/Recv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LakeServer is the server API for Lake service.
// All implementations must embed UnimplementedLakeServer
// for forward compatibility
type LakeServer interface {
	Send(context.Context, *SendReq) (*SendRes, error)
	Recv(context.Context, *RecvReq) (*RecvRes, error)
	mustEmbedUnimplementedLakeServer()
}

// UnimplementedLakeServer must be embedded to have forward compatible implementations.
type UnimplementedLakeServer struct {
}

func (UnimplementedLakeServer) Send(context.Context, *SendReq) (*SendRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedLakeServer) Recv(context.Context, *RecvReq) (*RecvRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recv not implemented")
}
func (UnimplementedLakeServer) mustEmbedUnimplementedLakeServer() {}

// UnsafeLakeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LakeServer will
// result in compilation errors.
type UnsafeLakeServer interface {
	mustEmbedUnimplementedLakeServer()
}

func RegisterLakeServer(s grpc.ServiceRegistrar, srv LakeServer) {
	s.RegisterService(&Lake_ServiceDesc, srv)
}

func _Lake_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LakeServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Lake/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LakeServer).Send(ctx, req.(*SendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lake_Recv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecvReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LakeServer).Recv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Lake/Recv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LakeServer).Recv(ctx, req.(*RecvReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Lake_ServiceDesc is the grpc.ServiceDesc for Lake service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lake_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Lake",
	HandlerType: (*LakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Lake_Send_Handler,
		},
		{
			MethodName: "Recv",
			Handler:    _Lake_Recv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lake.proto",
}
