// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/lake.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Lake_Publish_FullMethodName   = "/Lake/Publish"
	Lake_Subscribe_FullMethodName = "/Lake/Subscribe"
)

// LakeClient is the client API for Lake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LakeClient interface {
	Publish(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishRes, error)
	Subscribe(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (Lake_SubscribeClient, error)
}

type lakeClient struct {
	cc grpc.ClientConnInterface
}

func NewLakeClient(cc grpc.ClientConnInterface) LakeClient {
	return &lakeClient{cc}
}

func (c *lakeClient) Publish(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishRes, error) {
	out := new(PublishRes)
	err := c.cc.Invoke(ctx, Lake_Publish_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lakeClient) Subscribe(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (Lake_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &Lake_ServiceDesc.Streams[0], Lake_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &lakeSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lake_SubscribeClient interface {
	Recv() (*SubscribeRes, error)
	grpc.ClientStream
}

type lakeSubscribeClient struct {
	grpc.ClientStream
}

func (x *lakeSubscribeClient) Recv() (*SubscribeRes, error) {
	m := new(SubscribeRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LakeServer is the server API for Lake service.
// All implementations must embed UnimplementedLakeServer
// for forward compatibility
type LakeServer interface {
	Publish(context.Context, *PublishReq) (*PublishRes, error)
	Subscribe(*SubscribeReq, Lake_SubscribeServer) error
	mustEmbedUnimplementedLakeServer()
}

// UnimplementedLakeServer must be embedded to have forward compatible implementations.
type UnimplementedLakeServer struct {
}

func (UnimplementedLakeServer) Publish(context.Context, *PublishReq) (*PublishRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedLakeServer) Subscribe(*SubscribeReq, Lake_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedLakeServer) mustEmbedUnimplementedLakeServer() {}

// UnsafeLakeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LakeServer will
// result in compilation errors.
type UnsafeLakeServer interface {
	mustEmbedUnimplementedLakeServer()
}

func RegisterLakeServer(s grpc.ServiceRegistrar, srv LakeServer) {
	s.RegisterService(&Lake_ServiceDesc, srv)
}

func _Lake_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LakeServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lake_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LakeServer).Publish(ctx, req.(*PublishReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lake_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LakeServer).Subscribe(m, &lakeSubscribeServer{stream})
}

type Lake_SubscribeServer interface {
	Send(*SubscribeRes) error
	grpc.ServerStream
}

type lakeSubscribeServer struct {
	grpc.ServerStream
}

func (x *lakeSubscribeServer) Send(m *SubscribeRes) error {
	return x.ServerStream.SendMsg(m)
}

// Lake_ServiceDesc is the grpc.ServiceDesc for Lake service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lake_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Lake",
	HandlerType: (*LakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Lake_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Lake_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/lake.proto",
}
