version: "3.8"
services:
  agent-ha-0: # seed
    image: ghcr.io/h0n9/kistio-agent
    build:
      context: ./agent
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7780/quic
      - SEED=test-0
      - ENABLE_DHT_SERVER=true
    networks:
      agent-net:
  agent-ha-1:
    depends_on:
      - agent-ha-0
    image: ghcr.io/h0n9/kistio-agent
    build:
      context: ./agent
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7780/quic
      - BOOTSTRAPS=/dns4/agent-ha-0/udp/7780/quic/p2p/QmbXyJsL3wnWa864f3GLv8bno2KhC6kRA2d3akVETLEfPo
      - SEED=test-1
      - ENABLE_DHT_SERVER=true
    networks:
      agent-net:
  agent-ha-2:
    depends_on:
      - agent-ha-0
    image: ghcr.io/h0n9/kistio-agent
    build:
      context: ./agent
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7780/quic
      - BOOTSTRAPS=/dns4/agent-ha-0/udp/7780/quic/p2p/QmbXyJsL3wnWa864f3GLv8bno2KhC6kRA2d3akVETLEfPo
      - SEED=test-2
      - ENABLE_DHT_SERVER=true
    networks:
      agent-net:
  agent-0:
    depends_on:
      - agent-ha-0
    image: ghcr.io/h0n9/kistio-agent
    build:
      context: ./agent
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7780/quic
      - BOOTSTRAPS=/dns4/agent-ha-0/udp/7780/quic/p2p/QmbXyJsL3wnWa864f3GLv8bno2KhC6kRA2d3akVETLEfPo
      - GRPC_LISTEN=0.0.0.0:7788
      - ENABLE_DHT_SERVER=true
    networks:
      agent-net:
  client-0:
    depends_on:
      - agent-0
    image: ghcr.io/h0n9/sample-client
    build:
      context: ./sample-client
    environment:
      - AGENT_HOST=agent-0
      - AGENT_PORT=7788
      - TOPIC_PUB=balance
      - TOPIC_SUB=account
      - INTERVAL=1000
    networks:
      agent-net:
  agent-1:
    depends_on:
      - agent-ha-0
    image: ghcr.io/h0n9/kistio-agent
    build:
      context: ./agent
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7780/quic
      - BOOTSTRAPS=/dns4/agent-ha-0/udp/7780/quic/p2p/QmbXyJsL3wnWa864f3GLv8bno2KhC6kRA2d3akVETLEfPo
      - GRPC_LISTEN=0.0.0.0:7788
      - ENABLE_DHT_SERVER=true
    networks:
      agent-net:
  client-1:
    depends_on:
      - agent-1
    image: ghcr.io/h0n9/sample-client
    build:
      context: ./sample-client
    environment:
      - AGENT_HOST=agent-1
      - AGENT_PORT=7788
      - TOPIC_PUB=account
      - TOPIC_SUB=balance
      - INTERVAL=1000
    networks:
      agent-net:
networks:
  agent-net:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
