services:
  agent-0: # seed
    image: h0n9/kistio-agent:latest
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7788/quic
      - SEED=test-0
      - GRPC_LISTEN=0.0.0.0:7788
    ports:
      - 7780:7788
    networks:
      agent-net:
        ipv4_address: 172.19.0.2
  agent-1:
    depends_on:
      - agent-0
    image: h0n9/kistio-agent:latest
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7788/quic
      - BOOTSTRAPS=/ip4/172.19.0.2/udp/7788/quic/p2p/QmbXyJsL3wnWa864f3GLv8bno2KhC6kRA2d3akVETLEfPo
      - SEED=test-1
      - GRPC_LISTEN=0.0.0.0:7788
    ports:
      - 7781:7788
    networks:
      agent-net:
  agent-2:
    depends_on:
      - agent-0
    image: h0n9/kistio-agent:latest
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7788/quic
      - BOOTSTRAPS=/ip4/172.19.0.2/udp/7788/quic/p2p/QmbXyJsL3wnWa864f3GLv8bno2KhC6kRA2d3akVETLEfPo
      - SEED=test-2
      - GRPC_LISTEN=0.0.0.0:7788
    ports:
      - 7782:7788
    networks:
      agent-net:
networks:
  agent-net:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
