version: "3.8"
services:
  agent-ha-0: # seed
    image: h0n9/kistio-agent:latest
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7780/quic
      - SEED=test-0
      - ENABLE_DHT_SERVER=true
    networks:
      agent-net:
        ipv4_address: 172.19.0.2
  agent-ha-1:
    depends_on:
      - agent-ha-0
    image: h0n9/kistio-agent:latest
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7780/quic
      - BOOTSTRAPS=/ip4/172.19.0.2/udp/7780/quic/p2p/QmbXyJsL3wnWa864f3GLv8bno2KhC6kRA2d3akVETLEfPo
      - SEED=test-1
      - ENABLE_DHT_SERVER=true
    networks:
      agent-net:
  agent-ha-2:
    depends_on:
      - agent-ha-0
    image: h0n9/kistio-agent:latest
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7780/quic
      - BOOTSTRAPS=/ip4/172.19.0.2/udp/7780/quic/p2p/QmbXyJsL3wnWa864f3GLv8bno2KhC6kRA2d3akVETLEfPo
      - SEED=test-2
      - ENABLE_DHT_SERVER=true
    networks:
      agent-net:
  agent-0:
    depends_on:
      - agent-ha-0
    image: h0n9/kistio-agent:latest
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7780/quic
      - BOOTSTRAPS=/ip4/172.19.0.2/udp/7780/quic/p2p/QmbXyJsL3wnWa864f3GLv8bno2KhC6kRA2d3akVETLEfPo
      - GRPC_LISTEN=0.0.0.0:7788
      - ENABLE_DHT_SERVER=true
    networks:
      agent-net:
        ipv4_address: 172.19.1.2
  client-0:
    depends_on:
      - agent-0
    image: sample-client:latest
    environment:
      - AGENT_HOST=172.19.1.2
      - AGENT_PORT=7788
      - TOPIC_PUB=balance
      - TOPIC_SUB=account
    networks:
      agent-net:
  agent-1:
    depends_on:
      - agent-ha-0
    image: h0n9/kistio-agent:latest
    environment:
      - LISTENS=/ip4/0.0.0.0/udp/7780/quic
      - BOOTSTRAPS=/ip4/172.19.0.2/udp/7780/quic/p2p/QmbXyJsL3wnWa864f3GLv8bno2KhC6kRA2d3akVETLEfPo
      - GRPC_LISTEN=0.0.0.0:7788
      - ENABLE_DHT_SERVER=true
    networks:
      agent-net:
        ipv4_address: 172.19.1.3
  client-1:
    depends_on:
      - agent-1
    image: sample-client:latest
    environment:
      - AGENT_HOST=172.19.1.3
      - AGENT_PORT=7788
      - TOPIC_PUB=account
      - TOPIC_SUB=balance
    networks:
      agent-net:
networks:
  agent-net:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
