version: "3.8"

services:
  agent:
    build:
      context: .
    image: h0n9/msg-lake
    command: ["agent"]
    deploy:
      replicas: 10
  nginx:
    depends_on:
      - agent
    image: nginx:1.23.4-alpine3.17
    restart: always
    volumes:
      - ./misc/nginx.conf:/etc/nginx/conf.d/msg-lake.conf:ro
    ports:
      - 8080:8080
