name: redis-logger ci
on:
  push:
    tags:
      - "v*-redis-logger"
env:
  img-registry: ghcr.io
  img-repository: redis-logger
jobs:
  build-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.img-registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.img-registry }}/${{ env.img-repository }}:${GITHUB_REF/-redis-logger/''}
          cache-from: type=gha,scope=redis-logger
          cache-to: type=gha,mode=max,scope=redis-logger
