name: kistio-agent ci
on:
  push:
    tags:
      - v*-kistio-agent
env:
  img-registry: ghcr.io/h0n9
  img-repository: kistio-agent
  img-tag: latest
jobs:
  build-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.img-registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup img-tag
        shell: bash
        run: echo "img-tag=${GITHUB_REF_NAME/-kistio-agent/''}" >> $GITHUB_ENV
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: kistio/agent/
          push: true
          tags: ${{ env.img-registry }}/${{ env.img-repository }}:${{ env.img-tag }}
          cache-from: type=gha,scope=kistio-agent
          cache-to: type=gha,mode=max,scope=kistio-agent
