name: redis-logger ci
on:
  push:
    tags:
      - v*-redis-logger
env:
  img-registry: ghcr.io
  img-repository: redis-logger
  img-tag: latest
jobs:
  build-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.img-registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup img-tag
        shell: bash
        run: echo "img-tag=${GITHUB_REF_NAME/-redis-logger/''}" >> $GITHUB_ENV
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.img-registry }}/${{ env.img-repository }}:${{ env.img-tag }}
          cache-from: type=gha,scope=redis-logger
          cache-to: type=gha,mode=max,scope=redis-logger
